apiVersion: v1
kind: Service
metadata:
  name: frontend # Tên tổng đài nội bộ của Frontend
spec:
  type: LoadBalancer # Chuyển từ ClusterIP sang LoadBalancer để lấy IP trực tiếp từ MetalLB
  selector:
    app: frontend 
  ports:
    - port: 8888       # Đổi cổng đón khách thành 8888 theo ý bạn
      targetPort: 80 # Vẫn trỏ vào cổng 80 bên trong container Nginx của React
