apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  # Biến dành cho container Postgres khởi tạo DB
  POSTGRES_USER: shop_user
  POSTGRES_PASSWORD: shop_password
  
  # Biến dành cho Spring Boot Backend kết nối vào DB (Rất quan trọng!)
  SPRING_DATASOURCE_USERNAME: shop_user
  SPRING_DATASOURCE_PASSWORD: shop_password
