apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret # Tên của chiếc két sắt này
type: Opaque # Loại secret thông thường (dữ liệu bên dưới sẽ được K8s mã hóa base64)
stringData:
  POSTGRES_USER: shop_user # Tên đăng nhập DB
  POSTGRES_PASSWORD: shop_password # Mật khẩu DB (Không bao giờ nên push file này lên Github dạng rõ ràng trong thực tế)
